# Generated by Django 4.2.8 on 2024-09-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_comment_author_profile_picture_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
