# Generated by Django 4.2.8 on 2024-08-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expected_prices',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='categories_bought',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
