# Generated by Django 4.2.8 on 2024-09-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_expected_prices_alter_user_categories_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_data_in_comments',
            field=models.BooleanField(default=True, help_text='Регулирует, скрывать ли пользователиские данные, такие как имя и аватар в комментариях или нет.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
